# This makefile contains the instructions for compiling all exercises
# Some advanced functions are used, such as definition of the variables, CC, and references $@ and $<.

# C++ compiler
CC=g++

# All programs to be generated
all: program1 program2 program3 program4 program5 program6 program7

program1: exercise1.cpp
	$(CC) $< -o $@

program2: exercise2.cpp
	$(CC) $< -o $@

program3: exercise3.cpp
	$(CC) $< -o $@

program4: exercise4.cpp
	$(CC) $< -o $@

program5: exercise5.cpp
	$(CC) $< -o $@

program6: exercise6.cpp
	$(CC) $< -o $@

program7: exercise7.cpp
	$(CC) $< -o $@

clean:
	rm -f program1
	rm -f program2
	rm -f program3
	rm -f program4
	rm -f program5
	rm -f program6
	rm -f program7
	rm -f result.dat