# This makefile contains the instructions for compiling all exercises
# Some advanced functions are used, such as definition of the variables, CC, and references $@ and $<.

# C++ compiler
CC=g++

# All programs to be generated
all: program1 program2 program3 program4 program5 program6 program7 program8 program9

program1: Tutorial_1.cpp
	$(CC) -o $@ $<

program2: Tutorial_2.cpp
	$(CC) -o $@ $<

program3: Tutorial_3.cpp
	$(CC) -o $@ $<

program4: Tutorial_4.cpp
	$(CC) -o $@ $<

program5: Tutorial_5.cpp
	$(CC) -o $@ $<

program6: Tutorial_6.cpp
	$(CC) -o $@ $<

program7: Tutorial_7.cpp
	$(CC) -o $@ $<

program8: Tutorial_8.cpp
	$(CC) -o $@ $<

program9: Tutorial_9.cpp
	$(CC) -o $@ $<

clean:
	rm -f program1
	rm -f program2
	rm -f program3
	rm -f program4
	rm -f program5
	rm -f program6
	rm -f program7
	rm -f program8
	rm -f program9